### ISSUE TITLE
Select an initial target PFT

### ISSUE THREAD

**Issue by EliasMassoud1** [rubisco-sfa/MLEcohydrology#3]
Our initial attempts to assimilate the Lin2015 data have revealed that there is a great deal of variability in net assimilation that should be explained by environment/individual attributes that have not been recorded. In an attempt to remove some of that variability and also isolate a PFT which has many species and samples, we think it is a good idea at this point to work with a single PFT. We have [plots](https://www.climatemodeling.org/~nate/Lin2015_pft.html) of the Lin2015 data, separated by PFT and colored by species. Which one should we pick?

**Comment by nocollier** [comment]
From the plots it seems like it should be `broadleaf_deciduous_tree_temperate`,  `broadleaf_evergreen_tree_temperate`, or `needleleaf_evergreen_tree_temperate`

**Comment by EliasMassoud1** [comment]
It seems that Broadleaf Deciduous tree temperate would be a good first choice because it has a good data representation. Eventually it would be good to extend to testing of all 3 of these PFTs because they all have good data representation.

**Comment by nocollier** [comment]
Great, let's start with `broadleaf_deciduous_tree_temperate`
