### ISSUE TITLE
Commit FATES work similar to what we did with CLM5 (to github)

### ISSUE THREAD

**Issue by EliasMassoud1** [rubisco-sfa/MLEcohydrology#5]
https://github.com/rubisco-sfa/MLEcohydrology/pull/4

**Comment by EliasMassoud1** [comment]
This has been corrected now (see here: https://github.com/rubisco-sfa/MLEcohydrology/commit/4f27243cae02e82cdccb0b8a9a7effe0dea65843)

**Comment by nocollier** [comment]
For the future, leave this open until the branch is merged. It isn't 'done' until it is done!
